### ISSUE TITLE
Adapt aioxmlrpc for aiohttp 2.2

### ISSUE THREAD

**Issue by ludovic-gasc** [mardiros/aioxmlrpc#11]
Hi,

Thanks a lot for this library, we use it since a long time ago without issues.
However, since we have upgraded our application to aiohttp 2.2, we have an error in our logs each time we use aioxmlrpc, for example:

```
asyncio:ERROR 2017-08-09 13:26:49,300 base_events.py:1260 => Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f37747ecef0>
```

aiohttp have changed a lot of points with 2.X:
* http://aiohttp.readthedocs.io/en/stable/migration.html
* http://aiohttp.readthedocs.io/en/stable/changes.html

Is somebody working to upgrade aioxmlrpc for aiohttp 2.2 ?
Or are you interested in by a pull request for that ?

Regards.

**Comment by mardiros** [comment]
@GMLudo 

Nope, nobody is currently working on porting to aiohttp 2.2

If you have the time for that, a Pull Request is appreciate. Thanks!

**Comment by ludovic-gasc** [comment]
Hi @mardiros,

@ovv has worked to provide a PR for that.

Thanks for your feedback ;-)

**Comment by ludovic-gasc** [comment]
Hi @mardiros,

Thanks for the merge #12, I close now this issue.

Regards.
PS: If you will be at PyCON-FR 2017, I will offer you a beer ;-)
