### ISSUE TITLE
Update dependancies

### ISSUE THREAD

**Issue by IamMika23** [mardiros/aioxmlrpc#25]
Hey !

Can you please upgrade dependencies requirements ?

`aioxmlrpc 0.7.0 requires httpx<0.25.0,>=0.24.0, but you have httpx 0.27.0 which is incompatible.`

Thx

**Comment by mardiros** [comment]
Done. I've release aioxmlrpc 0.8.0 with httpx unfreeze for python >=3.7.

I did not remove python 3.7 compatibility yet.
