### ISSUE TITLE
context argument not available in xmlrpc.ServerProxy ?

### ISSUE THREAD

**Issue by zh0uquan** [mardiros/aioxmlrpc#6]
i would like to add ssl `context` to xmlrpcclient.ServerProxy, however it seems that it is not working with that, i checked axioxmlrpc package,  `context` seems not in aioxmlrpc.ServerProxy

**Comment by parmentelat** [comment]
I'd like to plus-one this issue

**Comment by IamMika23** [comment]
This thread is old but here is a workaround:
```
from aioxmlrpc.client import ServerProxy
import httpx

client = ServerProxy('https://your_url.here', session = httpx.AsyncClient(verify = False))
response = await client.your.xmlrpc.request
```

or any other SSL context

Hope it helps
